server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2_console

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: true
    open-in-view: false